export const AUTHENTICATION = 'AUTHENTICATION';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const UNAUTHORISED_ERROR = 'UNAUTHORISED_ERROR';
export const LOG_OUT = 'LOG_OUT';

export const SET_CLIENT_DETAILS = 'SET_CLIENT_DETAILS';
export const UPDATE_CLIENT_DETAILS = 'UPDATE_CLIENT_DETAILS';
export const UPDATE_CLIENT_LIST = 'UPDATE_CLIENT_LIST';
export const CLIENT_LIST = 'CLIENT_LIST';
